### ISSUE TITLE
Ckpts of a trained network

### ISSUE THREAD

**Issue by Magauiya** [ovshake/cobra#1]
Dear Abhishek Maiti,

Thank you for sharing your code and paper. I am very much interested in your work and would like to test COBRA for a cross-modal retrieval problem. So, can you kindly provide checkpoints for your model? 

Sincerely,
Magauiya

**Comment by ovshake** [comment]
Hi @Magauiya 
Thank you for your interest. We will release the weights for all the datasets very shortly.
